CREATE TABLE IF NOT EXISTS "CommercialApproval" (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "orderId" bigint NOT NULL REFERENCES "salesOrders"(id),
    "projectName" text NOT NULL,
    "designerId" bigint NOT NULL REFERENCES "appUsers"(id),
    "commercialRevisionRequest" text,
    "designerRevisionResponse" text,
    approved boolean NOT NULL DEFAULT false,
    "approvedAt" timestamptz,
    "createdAt" timestamptz NOT NULL DEFAULT now(),
    "updatedAt" timestamptz NOT NULL DEFAULT now(),
    "createdById" bigint REFERENCES "appUsers"(id),
    "updatedById" bigint REFERENCES "appUsers"(id)
);

ALTER TABLE "CommercialApproval" ENABLE ROW LEVEL SECURITY;

CREATE POLICY "commercial_approval_authenticated_all"
    ON "CommercialApproval"
    FOR ALL
    TO authenticated
    USING (true)
    WITH CHECK (true);
